### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by blackthornecl** [gaboflowers/servel-padron#1]
```
python2.6 luxuryParser.py -c Buin.pdf 
Traceback (most recent call last):
  File "luxuryParser.py", line 15, in <module>
    from py_circs import circ_nombres, region_nums
  File "/Users/psegovias/Desktop/servel-padron-master/py_circs.py", line 44
    region_nombre = {v: k for k, v in region_nums.iteritems()}
                            ^
SyntaxError: invalid syntax
```

Como dijo Gary, ¿Que Sucede?

Se agradece la ayuda.

**Comment by gaboflowers** [comment]
La verdad no veo por qué falló el generador. Prueba cambiando esa línea por:
```python
region_nombre = dict()
for tupla in region_nums.iteritems():
     (a,b) = tupla
     region_nombre[b] = a
```
